#!/bin/sh
#
# wpUpdateUrl runs the autoUpdateWpName script
#
# chkconfig:   345 95 5
# description: Runs the update script for WordPress to update name references \
#    in the database and configuration files.

### BEGIN INIT INFO
# Provides: one time WordPress name update on AWS
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 345
# Default-Stop: 95
# Short-Description: runs the "at" daemon
# Description:      Runs the update script for WordPress to update name references 
#   in the database and configuration files. 
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec=/usr/local/updateWordPressUrl/autoUpdateWpName
prog="wpUpdateUrl"

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    $exec 
    retval=$?
    echo
    [ $retval -eq 0 ] 
}

stop() {
 sleep 0
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
  sleep 0 
}


rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
